ingenium/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as django_auth_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from questions.urls import MainView, LandingView


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    path('', MainView.as_view(), name='main'), 

    path('welcome/', LandingView.as_view(), name='landing'), 
    path('users/', include('users.urls', namespace='users')),
    path('questions/', include('questions.urls', namespace='questions')), 
    path('votes/', include('votes.urls', namespace='votes')),

] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from .views import *


app_name = 'questions'

urlpatterns = [
    path('all-questions/', AllQuestionsView.as_view(), name='all_questions'), 
    path('all-categories/', AllCategoriesView.as_view(), name='all_categories'), 
    path('create-question/', CreateQuestionView.as_view(), name='create_question'),
    path('<int:year>/<int:month>/<int:day>/<slug:question_slug>/', SingleQuestionView.as_view(), name='single_question'),
    path('search/', SearchView.as_view(), name='search'), 
    path('category/<slug:category_slug>/', CategoryView.as_view(), name='category'), 
    path('tag/<slug:tag_slug>/', TagView.as_view(), name='tag'),
    path('get_tags/<int:category_id>', get_tags_by_category, name='get_tags')
]

users/urls.py
from django.urls import path, include
from .views import *


app_name = 'users'

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('register/', RegisterView.as_view(), name='register'), 
    path('verify-email/<uidb64>/<token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('verify-email/done/', VerifyEmailDoneView.as_view(), name='verify_email_done'),
    path('invalid-verification/', InvalidVerificationView.as_view(), name='invalid_verification'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('profile/', ProfileEditView.as_view(), name='profile'),
]

votes/urls.py
from django.urls import path, include
from .views import *


app_name = 'votes'

urlpatterns = [
    path('question/vote-up/', vote_up_for_question, name='vote_up_for_question'),
    path('question/vote-down/', vote_down_for_question, name='vote_down_for_question'),
    path('question/delete-vote/', delete_vote_for_question, name='delete_vote_for_question'),
]

questions/models.py
from django.db import models
from users.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import localtime
from unidecode import unidecode


class Category(models.Model): 
    title = models.CharField(max_length=30, null=False, unique=True) 
    description = models.CharField(max_length=200, null=False, unique=True) 
    slug = models.SlugField(max_length=200, null=False, default="", unique=True)

    def __str__(self) -> str: 
        return f'{self.title}'
    
    def get_absolute_url(self): 
        return reverse('questions:category', args=[self.slug])
    
    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        return super(Category, self).save(*args, **kwargs)
    

class Tag(models.Model): 
    text = models.CharField(max_length=50, null=False, unique=True)
    slug = models.SlugField(max_length=200, unique=True, null=False)
    category = models.ForeignKey(Category, null=False, default=1, on_delete=models.CASCADE, 
                                 related_name='tags')
    
    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.text))
        return super(Tag, self).save(*args, **kwargs)
    
    def get_absolute_url(self): 
        return reverse('questions:tag', args=[self.slug])
    
    def __str__(self) -> str:
        return f'{self.text}'


class Question(models.Model): 

    class Status(models.TextChoices): 
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликован'
        BANNED = 'BN', 'В бане'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions') 
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, related_name='categories')
    title = models.CharField(max_length=120, blank=False, null=False) 
    content = models.TextField(max_length=2000, blank=True, null=True) 
    created_at = models.DateTimeField(auto_now_add=True) 
    votes_count = models.IntegerField(default=0, null=False)
    answers_count = models.IntegerField(default=0, null=False)
    slug = models.SlugField(max_length=200, null=False, default="", unique=True)
    tags = models.ManyToManyField(Tag, related_name='questions', blank=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()

    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Question.Status.PUBLISHED) 
    published = PublishedManager()
        
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at'])
        ]

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        return super(Question, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.title} ({self.user.username})' 
    
    def get_absolute_url(self): 
        local_created_at = localtime(self.created_at)  
        return reverse('questions:single_question',
                       args=[local_created_at.year, local_created_at.month, local_created_at.day, self.slug])
     

class Answer(models.Model): 
    content = models.CharField(max_length=3000, null=False, blank=False) 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='answers') 
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False, related_name='answers') 
    created_at = models.DateTimeField(auto_now_add=True) 
    votes_count = models.IntegerField(default=0, null=False) 
    is_the_best = models.BooleanField(default=False) 

    def __str__(self) -> str: 
        return f'{self.user}: {self.content}'

questions/forms.py
from django import forms 
from .models import Answer, Question


class CreateAnswerForm(forms.ModelForm): 
    class Meta:
        model = Answer 
        fields = ['content'] 
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Введите свой ответ', 'rows': 3}),
        } 
        labels = {
            'content': '',
        } 


class CreateQuestionForm(forms.ModelForm): 
    class Meta: 
        model = Question 
        fields = ['title', 'content', 'category', 'tags'] 
        labels = {
            'title': 'Название', 
            'content': 'Содержание (опционально)', 
            'category': 'Категория', 
            'tags': 'Теги (опционально)',
        }
        widgets = {
            'content': forms.Textarea(attrs={'style': 'height: 80px',})
        }


class SearchForm(forms.Form):
    query = forms.CharField(max_length=30, label='', widget=forms.TextInput(attrs={
        'placeholder': 'Найти вопрос...', 
        'class': 'form-control me-2', 
    }))

questions/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.views.generic import TemplateView, FormView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.cache import cache
from ingenium.settings import CacheKeys
from questions.tasks import send_new_answer_notification_task
from .services import QuestionService, CategoryService, AnswerService, TagService, get_paginated_collection, SearchService
from votes.services import VoteForQuestionService
from .forms import CreateAnswerForm, CreateQuestionForm, SearchForm
from .models import Tag


class MainView(View): 
    def get(self, request): 
        if request.user.is_authenticated:
            return redirect('questions:all_questions')
        else: 
            return redirect('landing')


class LandingView(TemplateView): 
    template_name = 'questions/landing.html'


class AllQuestionsView(View): 
    template_name = 'questions/all_questions.html'

    def get(self, request): 
        questions = cache.get_or_set(CacheKeys.Static.ALL_QUESTIONS, 
                                     lambda: QuestionService.get_published_questions_sorted_by_votes().prefetch_related('tags').select_related('category'), 
                                     60)
        for question in questions: 
            question.has_tags = question.tags.exists()
        questions = get_paginated_collection(request, 
                                             collection=questions, 
                                             count_per_page=10)
        context = {
            'questions': questions,
        }
        return render(request, self.template_name, context)


class AllCategoriesView(TemplateView): 
    template_name = 'questions/all_categories.html'

    def get_context_data(self):
        all_categories = cache.get_or_set(CacheKeys.Static.ALL_CATEGORIES_WITH_TAGS, 
                                          lambda: CategoryService.get_all_categories().prefetch_related('tags'), 
                                          60 * 60 * 6)
        for category in all_categories: 
            category.has_tags = category.tags.exists()
        context = {'categories': all_categories }
        return context
    

class SingleQuestionView(View):  
    template_name = 'questions/single_question.html'
    form_class = CreateAnswerForm

    def get(self, request, year: int, month: int, day: int, question_slug: str): 
        question = QuestionService.get_published_question(year, month, day, question_slug)
        similar_questions = QuestionService.get_similar_questions(question)

        form = CreateAnswerForm()

        user_vote = None
        if request.user.is_authenticated:
            user_vote = VoteForQuestionService.get_vote_or_none(question.pk, request.user.pk)

        context = {
            'question': question,
            'similar_questions': similar_questions,
            'form': form, 
            'user_vote': user_vote
        } 

        return render(request, self.template_name, context) 
    
    def post(self, request, year: int, month: int, day: int, question_slug: str): 
        user = request.user 
        question = QuestionService.get_published_question(year, month, day, question_slug) 

        form = CreateAnswerForm(request.POST)
        if form.is_valid(): 
            answer_content = form.cleaned_data['content'] 
            AnswerService.create_and_publish_answer(answer_content, user, question) 
            

            if question.user_id != user.pk and question.answers_count < 20:
                send_new_answer_notification_task.delay(question.user_id, question.pk)

            return redirect('questions:single_question', 
                            year=question.created_at.year,
                            month=question.created_at.month, 
                            day=question.created_at.day, 
                            question_slug=question.slug)

        context = {
            'question': question,
            'form': form,
        }
        return render(request, self.template_name, context) 
    

@method_decorator(login_required, name='dispatch')
class CreateQuestionView(FormView): 
    template_name = 'questions/create_question.html' 
    form_class = CreateQuestionForm

    def form_valid(self, form: CreateQuestionForm) -> HttpResponse:
        cd = form.cleaned_data
        title = cd['title']
        content = cd['content']
        category = cd['category'] 
        tags = cd['tags']
        user = self.request.user

        cache.delete(CacheKeys.Dynamic.questions_by_category(category.slug))

        QuestionService.create_and_publish_question(title, category, user, content, tags)

        return redirect('questions:all_questions')
    

class CategoryView(View): 
    template_name = 'questions/questions_in_category.html' 

    def get(self, request, category_slug: str): 
        cache.get
        category = cache.get_or_set(CacheKeys.Dynamic.category(category_slug), 
                                    lambda: CategoryService.get_category_by_slug(category_slug), 
                                    60 * 60 * 6) 
        questions = cache.get_or_set(CacheKeys.Dynamic.questions_by_category(category_slug), 
                                     lambda: QuestionService.get_published_questions_for_category(category), 
                                     60 * 10)
        questions = get_paginated_collection(request, 
                                             collection=questions, 
                                             count_per_page=10)
        context = {
            'questions': questions, 
            'category': category,
        }
        return render(request, self.template_name, context)  
    

class TagView(View): 
    template_name = 'questions/questions_with_tag.html' 

    def get(self, request, tag_slug: str): 
        tag = TagService.get_tag_by_slug(tag_slug)
        questions = QuestionService.get_published_questions_with_tag(tag).prefetch_related('tags').select_related('category')
        for question in questions: 
            question.has_tags = question.tags.exists()

        questions = get_paginated_collection(request, collection=questions)

        context = {
            'questions': questions, 
            'tag': tag,
        }
        return render(request, self.template_name, context)   
    

class SearchView(View): 
    def get(self, request): 
        form = SearchForm(request.GET) 

        if form.is_valid():
            query = form.cleaned_data.get('query') 
            questions = SearchService.search_questions_by_query(query)
            paginated_questions = get_paginated_collection(self.request, collection=questions)
            context = {
                'query': query, 
                'questions': paginated_questions
            }
            return render(request, 'questions/search_result.html', context) 
        else: 
            pass 


def get_tags_by_category(request, category_id: int) -> JsonResponse:
    tags = Tag.objects.filter(category_id=category_id).values('id', 'text')
    return JsonResponse(list(tags), safe=False) 

questions/templates/questions/create_question.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Задать вопрос
{% endblock title %}

{% block content %}
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <p class="text-center mb-2 h2 font-jost">Опубликовать свой вопрос</p>

            <form method="post" action="{{ rquest.path }}">
                {% csrf_token %}
                <div class="mb-3 font-no fs-6">
                    {{ form.title | as_crispy_field }}
                </div>

                <div class="mb-3 font-no fs-6">
                    {{ form.content | as_crispy_field }}
                </div>

                <div class="mb-3 font-no fs-6">
                    {{ form.category | as_crispy_field }}
                </div>

                <div class="mb-3 font-no fs-6">
                    {{ form.tags | as_crispy_field }}
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-dark">Опубликовать вопрос</button>
                </div>
            </form>

        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const categorySelect = document.getElementById('id_category');
        const tagsSelect = document.getElementById('id_tags');
    
        categorySelect.addEventListener('change', function () {
            const categoryId = this.value;
            const url = `{% url 'questions:get_tags' 0 %}`.replace('0', categoryId);
            fetch(url)
                .then(response => response.json())
                .then(data => {
                    tagsSelect.innerHTML = '';
                    data.forEach(tag => {
                        const option = document.createElement('option');
                        option.value = tag.id;
                        option.text = tag.text;
                        tagsSelect.appendChild(option);
                    });
                });
        });
    });
</script>
{% endblock content %}

questions/templates/questions/landing.html
{% extends "base.html" %}

{% block title %}
Добро пожаловать на Ingenium
{% endblock title %}

{% block content %}
<header class="bg-light text-dark py-5">
    <div class="container text-center">
        <h1 class="display-4 fw-bold">Ingenium — Платформа знаний и вопросов</h1>
        <p class="lead">Задавайте вопросы, делитесь знаниями и находите ответы на самые важные для вас темы.</p>
        <a href="{% url 'questions:create_question' %}" class="btn btn-dark btn-lg mt-3">Задать свой вопрос</a>
    </div>
</header>

<section class="py-5">
    <div class="container">
        <div class="row">

            <div class="col-lg-4 text-center">
                <i class="fas fa-question-circle fa-3x mb-3 text-primary"></i>
                <h3 class="h5">Задавайте вопросы</h3>
                <p>Получите ответ на любой интересующий вас вопрос. Наша платформа охватывает множество тем и категорий.</p>
            </div>

            <div class="col-lg-4 text-center">
                <i class="fas fa-lightbulb fa-3x mb-3 text-primary"></i>
                <h3 class="h5">Делитесь знаниями</h3>
                <p>Делитесь своим опытом и знаниями, помогая другим пользователям найти ответы на их вопросы.</p>
            </div>

            <div class="col-lg-4 text-center">
                <i class="fas fa-tags fa-3x mb-3 text-primary"></i>
                <h3 class="h5">Открывайте категории</h3>
                <p>Исследуйте разнообразные категории и находите темы, которые вас интересуют больше всего.</p>
            </div>

        </div>
    </div>
</section>

<section class="bg-dark text-light py-5">
    <div class="container text-center">
        <h2 class="h3 fw-bold">Почему стоит выбрать Ingenium?</h2>
        <p class="lead mb-4">Мы объединяем людей, чтобы они могли учиться и развиваться вместе.</p>
        <div class="row">

            <div class="col-md-4">
                <h4 class="h5">Множество категорий</h4>
                <p>У нас вы найдете темы от технологий до искусства.</p>
            </div>

            <div class="col-md-4">
                <h4 class="h5">Активное сообщество</h4>
                <p>Наши пользователи активно задают и отвечают на вопросы, помогая друг другу.</p>
            </div>

            <div class="col-md-4">
                <h4 class="h5">Простота и удобство</h4>
                <p>Интуитивный интерфейс делает использование сайта легким и приятным.</p>
            </div>

        </div>
        <a href="{% url 'questions:all_questions' %}" class="btn btn-outline-light btn-lg mt-4">Посмотреть вопросы</a>
    </div>
</section>

<section class="py-5">
    <div class="container">
        <div class="container text-center">

            <div>
                <h2 class="h3 fw-bold">Присоединяйтесь к нам сегодня</h2>
                <p>Зарегистрируйтесь и начните задавать свои вопросы или помогать другим.</p>
                <a href="{% url 'users:register' %}" class="btn btn-dark btn-lg">Зарегистрироваться</a>
            </div>

        </div>
    </div>
</section>

{% endblock content %}

questions/templates/questions/single_question.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load questions_tags %}

{% block title %}
    Ingenium
{% endblock title %}

{% block content %}

<div class="container">
    <div class="container-fluid">
        <div class="row align-items-start">

            {% show_sidebar_categories %}
        
            <div class="col">

                <div>
                    <div>
                        <p class="font-jost h5">Автор вопроса: {{ question.user.username }}</p>
                    </div>

                    <div>
                        <p class="font-jost">{{ question.created_at | date:"d.m.Y H:i" }}</p>
                    </div>
                </div>
                
                <hr>

                <div style="display: flex;">
                    
                    <div class="ms-3 mt-4 me-4 text-center">
                        <div class="mb-1">
                            <input type="radio"
                            class="btn-check vote-button" id="btnVoteUp" 
                            name="vote" autocomplete="off"
                            {% if user_vote and user_vote.is_up %}checked data-action="deleteVote"{% else %}data-action="voteUp"{% endif %}>
                            <label class="btn btn-outline-dark" for="btnVoteUp"><p class="h5">↑</p></label>
                        </div>

                        <div class="mt-2 mb-2">
                            <p id="questionVotesCount" class="h5">{{ question.votes_count }}</p>
                        </div>
                    
                        <div>
                            <input type="radio" 
                            class="btn-check vote-button" id="btnVoteDown" 
                            name="vote" autocomplete="off"
                            {% if user_vote and user_vote.is_down %}checked data-action="deleteVote"{% else %}data-action="voteDown"{% endif %}>
                            <label class="btn btn-outline-dark" for="btnVoteDown"><p class="h5">↓</p></label>
                        </div>
                    </div>
                

                    <div class="mt-4 mb-4">
                        <div>
                            <p class="h2 font-pt-serif">{{ question.title }}</p>
                        </div>
                        <div>
                            <p>
                                {{ question.content }}
                            </p>
                        </div>
                    </div>
                </div>

                <!-- Similar questions -->
                {% if similar_questions %}
                <div class="mt-4">
                    <h4 class="font-pt-serif">Похожие вопросы</h4>
                    <div class="list-group">
                        {% for similar_question in similar_questions %}
                            <a href="{{ similar_question.get_absolute_url }}" class="list-group-item list-group-item-action">
                                <p class="mb-1">{{ similar_question.title }}</p>
                            </a>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}

                <hr>

                <div class="mt-3">

                    {% if request.user.is_authenticated %}
                        <div class="mb-4">
                            <form action="{{ question.get_absolute_url }}" method="post">
                                {% csrf_token %}
                                <div class="form-floating mb-3">
                                    {{ form.content | as_crispy_field }}
                                </div>

                                <div>
                                    <button class="btn btn btn-dark" type="submit">Отправить</button>
                                </div>
                                
                            </form>
                        </div>
                    {% else %}
                        <div class="pt-4 pb-4">
                            <p class="text-body-secondary font-noto-sans h5">
                                <a class="link-dark link-offset-3 link-offset-2-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'users:register' %}">
                                    Зарегистрируйтесь
                                </a> 
                                или 
                                <a class="link-dark link-offset-3 link-offset-2-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover" href="{% url 'users:login' %}">
                                    войдите в аккаунт
                                </a>, чтобы дать свой ответ
                            </p>
                        </div>
                    {% endif %}      
                    
                    <div class="mb-3">
                        <p class="h4 font-pt-serif">Ответы ({{ question.answers.count }})</p>
                    </div>
                    
                    {% for answer in question.answers.all %} 
                        <div class="card mb-3 {% if answer.is_the_best %} text-bg-success {% endif %}">
                            
                            <div class="card-body ">
                                <h6 class="card-subtitle mb-2" >{{ answer.user.username }}</h6>
                                {{ answer.content }}
                                <div>
                                    <p class="card-text text-end"><small class="text-body-secondary">{{ answer.created_at | date:"d.m.Y H:i" }}</small></p>
                                </div>
                            </div>
                        </div>
                    
                    {% empty %}
                        <div>
                            <p>Ответов на этот вопрос пока нет...</p>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
</div>


<!-- Registration/Login Modal -->
<div class="modal fade" id="authModal" tabindex="-1" aria-labelledby="authModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="authModalLabel">Вам нужно войти в систему</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          Пожалуйста, <a href="{% url 'users:login' %}">войдите в систему</a> или <a href="{% url 'users:register' %}">зарегистрируйтесь</a>, чтобы проголосовать.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

{% block domready %} 
<script>
const API_URLS = {
    voteUp: "{% url 'votes:vote_up_for_question' %}",
    voteDown: "{% url 'votes:vote_down_for_question' %}",
    deleteVote: "{% url 'votes:delete_vote_for_question' %}"
};

const ERROR_MESSAGES = {
    unexpected: "An unexpected error occurred.",
    missingElement: "Element is missing."
};

const BUTTON_IDS = {
    buttonVoteUp: "btnVoteUp", 
    buttonVoteDown: "btnVoteDown"
}

const actionButtons = document.querySelectorAll('.vote-button');
actionButtons.forEach(button => {
    button.addEventListener('click', () => {
        const action = button.dataset.action;

        const isAuthenticated = "{{ user.is_authenticated|yesno:'true,false' }}" === "true";
        if (isAuthenticated) {
            // Change vote count immediately
            updateVotesCountOnClick(action);
            saveVotesCount(action);
            changeButtonState(button);
        } else {
            showRegistrationBanner();
            uncheckAllButtons(actionButtons);
        }
    });
});

async function saveVotesCount(action) {
    try {
        const formData = new FormData();
        formData.append("question_id", "{{ question.pk }}");

        const url = API_URLS[action];
        const headers = {
            "X-CSRFToken": "{{ csrf_token }}"
        };
        const options = {
            method: "POST",
            headers: headers,
            mode: "same-origin",
            body: formData
        };

        const response = await fetch(url, options);
        const data = await response.json();
    } catch (error) {
        handleError(ERROR_MESSAGES.unexpected);
    }
}

function updateVotesCountOnClick(action) {
    const votesCountElement = document.getElementById("questionVotesCount");
    let currentCount = parseInt(votesCountElement.textContent, 10);
    const buttonUp = document.getElementById(BUTTON_IDS.buttonVoteUp);
    const buttonDown = document.getElementById(BUTTON_IDS.buttonVoteDown);
    
    console.log("buttonUp checked:", buttonUp.checked);
    console.log("buttonDown checked:", buttonDown.checked);

    if (action === "voteUp") {
        if (buttonDown.dataset.action == "deleteVote") {
            currentCount += 2; 
        } else {
            currentCount += 1; 
        }
    } else if (action === "voteDown") {
        if (buttonUp.dataset.action == "deleteVote") {
            currentCount -= 2; 
        } else {
            currentCount -= 1; 
        }
    } else if (action === "deleteVote") {
        if (buttonUp.dataset.action == "deleteVote") {
            currentCount -= 1; 
        } else if (buttonDown.dataset.action == "deleteVote") {
            currentCount += 1; 
        }
    }

    votesCountElement.textContent = currentCount;
}

function handleError(message) {
    console.error(message);
}

function changeButtonState(button) {
    let action = button.dataset.action;
    const buttonUp = document.getElementById(BUTTON_IDS.buttonVoteUp);
    const buttonDown = document.getElementById(BUTTON_IDS.buttonVoteDown);

    if (action === "voteUp") {
        buttonUp.checked = true;
        buttonDown.checked = false;
        button.dataset.action = "deleteVote";
        buttonDown.dataset.action = "voteDown";

    } else if (action === "voteDown") {
        buttonDown.checked = true;
        buttonUp.checked = false;
        button.dataset.action = "deleteVote";
        buttonUp.dataset.action = "voteUp";
        
    } else if (action === "deleteVote") {
        if (button.id === BUTTON_IDS.buttonVoteUp) {
            button.checked = false;
            button.dataset.action = "voteUp";
        } else if (button.id === BUTTON_IDS.buttonVoteDown) {
            button.checked = false;
            button.dataset.action = "voteDown";
        }
    }

    console.log(button.checked)
}

function showRegistrationBanner() {
    const authModal = new bootstrap.Modal(document.getElementById('authModal'));
    authModal.show();
}

function uncheckAllButtons(buttons) {
    buttons.forEach(button => {
        button.checked = false;
    });
}
</script>
{% endblock %}