ingenium/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as django_auth_views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from questions.urls import MainView, LandingView


urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('django.contrib.auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

    path('', MainView.as_view(), name='main'), 

    path('welcome/', LandingView.as_view(), name='landing'), 
    path('users/', include('users.urls', namespace='users')),
    path('questions/', include('questions.urls', namespace='questions')), 
    path('votes/', include('votes.urls', namespace='votes')),

] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from .views import *


app_name = 'questions'

urlpatterns = [
    path('all-questions/', AllQuestionsView.as_view(), name='all_questions'), 
    path('all-categories/', AllCategoriesView.as_view(), name='all_categories'), 
    path('create-question/', CreateQuestionView.as_view(), name='create_question'),
    path('<int:year>/<int:month>/<int:day>/<slug:question_slug>/', SingleQuestionView.as_view(), name='single_question'),
    path('search/', SearchView.as_view(), name='search'), 
    path('category/<slug:category_slug>/', CategoryView.as_view(), name='category'), 
    path('tag/<slug:tag_slug>/', TagView.as_view(), name='tag'),
    path('get_tags/<int:category_id>', get_tags_by_category, name='get_tags')
]

users/urls.py
from django.urls import path, include
from .views import *


app_name = 'users'

urlpatterns = [
    path('auth/', include('django.contrib.auth.urls')),
    path('register/', RegisterView.as_view(), name='register'), 
    path('verify-email/<uidb64>/<token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('verify-email/done/', VerifyEmailDoneView.as_view(), name='verify_email_done'),
    path('invalid-verification/', InvalidVerificationView.as_view(), name='invalid_verification'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', PasswordChangeView.as_view(), name='password_change'),
    path('profile/', ProfileEditView.as_view(), name='profile'),
]

questions/models.py
from django.db import models
from users.models import User
from django.urls import reverse
from django.utils.text import slugify
from django.utils.timezone import localtime
from unidecode import unidecode


class Category(models.Model): 
    title = models.CharField(max_length=30, null=False, unique=True) 
    description = models.CharField(max_length=200, null=False, unique=True) 
    slug = models.SlugField(max_length=200, null=False, default="", unique=True)

    def __str__(self) -> str: 
        return f'{self.title}'
    
    def get_absolute_url(self): 
        return reverse('questions:category', args=[self.slug])
    
    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        return super(Category, self).save(*args, **kwargs)
    

class Tag(models.Model): 
    text = models.CharField(max_length=50, null=False, unique=True)
    slug = models.SlugField(max_length=200, unique=True, null=False)
    category = models.ForeignKey(Category, null=False, default=1, on_delete=models.CASCADE, 
                                 related_name='tags')
    
    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.text))
        return super(Tag, self).save(*args, **kwargs)
    
    def get_absolute_url(self): 
        return reverse('questions:tag', args=[self.slug])
    
    def __str__(self) -> str:
        return f'{self.text}'


class Question(models.Model): 

    class Status(models.TextChoices): 
        DRAFT = 'DF', 'Черновик'
        PUBLISHED = 'PB', 'Опубликован'
        BANNED = 'BN', 'В бане'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions') 
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, related_name='categories')
    title = models.CharField(max_length=120, blank=False, null=False) 
    content = models.TextField(max_length=2000, blank=True, null=True) 
    created_at = models.DateTimeField(auto_now_add=True) 
    votes_count = models.IntegerField(default=0, null=False)
    answers_count = models.IntegerField(default=0, null=False)
    slug = models.SlugField(max_length=200, null=False, default="", unique=True)
    tags = models.ManyToManyField(Tag, related_name='questions', blank=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager()

    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Question.Status.PUBLISHED) 
    published = PublishedManager()
        
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at'])
        ]

    def save(self, *args, **kwargs):
        self.slug = slugify(unidecode(self.title))
        return super(Question, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return f'{self.title} ({self.user.username})' 
    
    def get_absolute_url(self): 
        local_created_at = localtime(self.created_at)  
        return reverse('questions:single_question',
                       args=[local_created_at.year, local_created_at.month, local_created_at.day, self.slug])
     

class Answer(models.Model): 
    content = models.CharField(max_length=3000, null=False, blank=False) 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False, related_name='answers') 
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=False, related_name='answers') 
    created_at = models.DateTimeField(auto_now_add=True) 
    votes_count = models.IntegerField(default=0, null=False) 
    is_the_best = models.BooleanField(default=False) 

    def __str__(self) -> str: 
        return f'{self.user}: {self.content}'

questions/forms.py
from django import forms 
from .models import Answer, Question


class CreateAnswerForm(forms.ModelForm): 
    class Meta:
        model = Answer 
        fields = ['content'] 
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Введите свой ответ', 'rows': 3}),
        } 
        labels = {
            'content': '',
        } 


class CreateQuestionForm(forms.ModelForm): 
    class Meta: 
        model = Question 
        fields = ['title', 'content', 'category', 'tags'] 
        labels = {
            'title': 'Название', 
            'content': 'Содержание (опционально)', 
            'category': 'Категория', 
            'tags': 'Теги (опционально)',
        }
        widgets = {
            'content': forms.Textarea(attrs={'style': 'height: 80px',})
        }


class SearchForm(forms.Form):
    query = forms.CharField(max_length=30, label='', widget=forms.TextInput(attrs={
        'placeholder': 'Найти вопрос...', 
        'class': 'form-control me-2', 
    }))

questions/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.views.generic import TemplateView, FormView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.cache import cache
from ingenium.settings import CacheKeys
from questions.tasks import send_new_answer_notification_task
from .services import QuestionService, CategoryService, AnswerService, TagService, get_paginated_collection, SearchService
from votes.services import VoteForQuestionService
from .forms import CreateAnswerForm, CreateQuestionForm, SearchForm
from .models import Tag


class MainView(View): 
    def get(self, request): 
        if request.user.is_authenticated:
            return redirect('questions:all_questions')
        else: 
            return redirect('landing')


class LandingView(TemplateView): 
    template_name = 'questions/landing.html'


class AllQuestionsView(View): 
    template_name = 'questions/all_questions.html'

    def get(self, request): 
        questions = cache.get_or_set(CacheKeys.Static.ALL_QUESTIONS, 
                                     lambda: QuestionService.get_published_questions_sorted_by_votes().prefetch_related('tags').select_related('category'), 
                                     60)
        for question in questions: 
            question.has_tags = question.tags.exists()
        questions = get_paginated_collection(request, 
                                             collection=questions, 
                                             count_per_page=10)
        context = {
            'questions': questions,
        }
        return render(request, self.template_name, context)


class AllCategoriesView(TemplateView): 
    template_name = 'questions/all_categories.html'

    def get_context_data(self):
        all_categories = cache.get_or_set(CacheKeys.Static.ALL_CATEGORIES_WITH_TAGS, 
                                          lambda: CategoryService.get_all_categories().prefetch_related('tags'), 
                                          60 * 60 * 6)
        for category in all_categories: 
            category.has_tags = category.tags.exists()
        context = {'categories': all_categories }
        return context
    

class SingleQuestionView(View):  
    template_name = 'questions/single_question.html'
    form_class = CreateAnswerForm

    def get(self, request, year: int, month: int, day: int, question_slug: str): 
        question = QuestionService.get_published_question(year, month, day, question_slug)
        similar_questions = QuestionService.get_similar_questions(question)

        form = CreateAnswerForm()

        user_vote = None
        if request.user.is_authenticated:
            user_vote = VoteForQuestionService.get_vote_or_none(question.pk, request.user.pk)

        context = {
            'question': question,
            'similar_questions': similar_questions,
            'form': form, 
            'user_vote': user_vote
        } 

        return render(request, self.template_name, context) 
    
    def post(self, request, year: int, month: int, day: int, question_slug: str): 
        user = request.user 
        question = QuestionService.get_published_question(year, month, day, question_slug) 

        form = CreateAnswerForm(request.POST)
        if form.is_valid(): 
            answer_content = form.cleaned_data['content'] 
            AnswerService.create_and_publish_answer(answer_content, user, question) 
            

            if question.user_id != user.pk and question.answers_count < 20:
                send_new_answer_notification_task.delay(question.user_id, question.pk)

            return redirect('questions:single_question', 
                            year=question.created_at.year,
                            month=question.created_at.month, 
                            day=question.created_at.day, 
                            question_slug=question.slug)

        context = {
            'question': question,
            'form': form,
        }
        return render(request, self.template_name, context) 
    

@method_decorator(login_required, name='dispatch')
class CreateQuestionView(FormView): 
    template_name = 'questions/create_question.html' 
    form_class = CreateQuestionForm

    def form_valid(self, form: CreateQuestionForm) -> HttpResponse:
        cd = form.cleaned_data
        title = cd['title']
        content = cd['content']
        category = cd['category'] 
        tags = cd['tags']
        user = self.request.user

        cache.delete(CacheKeys.Dynamic.questions_by_category(category.slug))

        QuestionService.create_and_publish_question(title, category, user, content, tags)

        return redirect('questions:all_questions')
    

class CategoryView(View): 
    template_name = 'questions/questions_in_category.html' 

    def get(self, request, category_slug: str): 
        cache.get
        category = cache.get_or_set(CacheKeys.Dynamic.category(category_slug), 
                                    lambda: CategoryService.get_category_by_slug(category_slug), 
                                    60 * 60 * 6) 
        questions = cache.get_or_set(CacheKeys.Dynamic.questions_by_category(category_slug), 
                                     lambda: QuestionService.get_published_questions_for_category(category), 
                                     60 * 10)
        questions = get_paginated_collection(request, 
                                             collection=questions, 
                                             count_per_page=10)
        context = {
            'questions': questions, 
            'category': category,
        }
        return render(request, self.template_name, context)  
    

class TagView(View): 
    template_name = 'questions/questions_with_tag.html' 

    def get(self, request, tag_slug: str): 
        tag = TagService.get_tag_by_slug(tag_slug)
        questions = QuestionService.get_published_questions_with_tag(tag).prefetch_related('tags').select_related('category')
        for question in questions: 
            question.has_tags = question.tags.exists()

        questions = get_paginated_collection(request, collection=questions)

        context = {
            'questions': questions, 
            'tag': tag,
        }
        return render(request, self.template_name, context)   
    

class SearchView(View): 
    def get(self, request): 
        form = SearchForm(request.GET) 

        if form.is_valid():
            query = form.cleaned_data.get('query') 
            questions = SearchService.search_questions_by_query(query)
            paginated_questions = get_paginated_collection(self.request, collection=questions)
            context = {
                'query': query, 
                'questions': paginated_questions
            }
            return render(request, 'questions/search_result.html', context) 
        else: 
            pass 


def get_tags_by_category(request, category_id: int) -> JsonResponse:
    tags = Tag.objects.filter(category_id=category_id).values('id', 'text')
    return JsonResponse(list(tags), safe=False) 

questions/templates/questions/includes/question_in_list.html
<div class="d-flex mb-1 shadow-sm">

    <div class="text-center pt-4 ms-4">
        <div class="mb-2 text-muted">
            <span class="d-block">{{ question.votes_count }}</span>
            <small>голосов</small>
        </div>
        <div class="mb-2 text-muted">
            <span class="d-block">{{ question.answers_count }}</span>
            <small>ответов</small>
        </div>
    </div>

    <div class="card py-1 px-4 border-0 flex-grow-1">
        <div class="card-body">
            <div class="mb-1">
                <h5 class="h4 font-pt-serif fs-5">
                    <a href="{{ question.get_absolute_url }}" class="text-dark text-decoration-none">
                        {{ question.title }}
                    </a>
                </h5>
            </div>

            <div class="mb-1">
                <p class="card-text font-noto-sans small">
                    {{ question.content | truncatewords_html:20 }}
                </p>
            </div>

            <p class="my-0 text-secondary small">
                Категория:
                <a class="card-link text-secondary " href="{{ question.category.get_absolute_url }}">
                    {{ question.category }}
                </a>
            </p>

            {% if question.has_tags %}
                <p class="my-0 small">
                    <b>
                        {% for tag in question.tags.all %}
                            <a href="{{ tag.get_absolute_url }}" class="font-pt-serif text-secondary me-2">{{ tag.text }}</a>
                        {% endfor %}
                    </b>
                </p>
            {% endif %}

            <div class="mt-1">
                <p class="card-text">
                    <small>
                        <i class="far fa-clock"></i> {{ question.created_at | date:"d.m.Y H:i" }}
                    </small>
                </p>
            </div>
        </div>
    </div>
</div>

questions/templates/questions/includes/question_in_list_without_category.html
<div class="d-flex mb-1 shadow-sm">

    <div class="text-center pt-4 ms-4">
        <div class="mb-2 text-muted">
            <span class="d-block">{{ question.votes_count }}</span>
            <small>голосов</small>
        </div>
        <div class="mb-2 text-muted">
            <span class="d-block">{{ question.answers_count }}</span>
            <small>ответов</small>
        </div>
    </div>

    <div class="card py-1 px-4 border-0 flex-grow-1">
        <div class="card-body">
            <div class="mb-1">
                <h5 class="h4 font-pt-serif fs-5">
                    <a href="{{ question.get_absolute_url }}" class="text-dark text-decoration-none">
                        {{ question.title }}
                    </a>
                </h5>
            </div>

            <div class="mb-1">
                <p class="card-text font-noto-sans small">
                    {{ question.content | truncatewords_html:20 }}
                </p>
            </div>

            {% if question.has_tags %}
                <p class="my-0 small">
                    <b>
                        {% for tag in question.tags.all %}
                            <a href="{{ tag.get_absolute_url }}" class="font-pt-serif text-secondary me-2">{{ tag.text }}</a>
                        {% endfor %}
                    </b>
                </p>
            {% endif %}

            <div class="mt-1">
                <p class="card-text">
                    <small>
                        <i class="far fa-clock"></i> {{ question.created_at | date:"d.m.Y H:i" }}
                    </small>
                </p>
            </div>
        </div>
    </div>
</div>

questions/templates/questions/includes/search_form.html
{% load crispy_forms_tags %}

<form action="{% url 'questions:search' %}" method="GET" class="d-flex" role="search">
    <div>
        {{ form.query | as_crispy_field }}
    </div>
    <button class="btn btn-outline-light" type="submit">Поиск</button>
</form>

questions/templates/questions/includes/sidebar.html
<div class="col-md-3 d-md-block d-none lex-column align-items-start">

    <div class="mb-3">
        <h3 class="font-jost"><a style="text-decoration: none; color: black;" href="{% url 'questions:all_categories' %}">Категории</a></h3>
    </div>

    {% for category in categories %}
        <div class="mb-2">
            <a href="{{ category.get_absolute_url }}" class="link-dark link-offset-2 link-offset-2-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                <p>{{ category.title }}</p>
            </a>
        </div>
    {% endfor %}

</div>